### ISSUE TITLE
Update function does not work when one of the sources has issues

### ISSUE THREAD

**Issue by silpheel** [antiwinter/wowa#49]
While writing the ticket it started working again, but for a short while this morning, I was unable to launch the update command. 
- `ls` and `search` worked fine
- Since I noticed, the issue lasted about 15 minutes but I don't know how long it was going on before I noticed it.
- I got 2 errors and both seem related to the mmoui api, I suppose they changed while the api issue was being fixed.

External errors cannot be prevented of course, however it would be good if in such cases the source was ignored temporarily (with a message for example) and the update could continue with the sources that are available.

Here are the error messages, partially obscured, in case they are useful.

Error type 1:
```
>wowa update

Updating database...mmoui summary failed TypeError: Cannot read property 'map' of null
    at C:\ProgramData\nvm\v12.18.3\node_modules\wowa\source\mmoui.js:41:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Error type 2:

```
>wowa update

Updating database...mmoui summary failed GotError [HTTPError]: Response code 520 (Origin Error)
    at EventEmitter.<anonymous> (C:\ProgramData\nvm\v12.18.3\node_modules\wowa\node_modules\got\source\as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  host: 'api.mmoui.com',
  hostname: 'api.mmoui.com',
  method: 'GET',
  path: '/v3/game/WOW/filelist.json',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://api.mmoui.com/v3/game/WOW/filelist.json',
  gotOptions: {
    path: '/v3/game/WOW/filelist.json',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'api.mmoui.com',
    port: null,
    hostname: 'api.mmoui.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/v3/game/WOW/filelist.json',
    href: 'https://api.mmoui.com/v3/game/WOW/filelist.json',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 520,
  statusMessage: 'Origin Error',
  headers: {
    date: 'Sat, 19 Dec 2020 12:44:46 GMT',
    'content-type': 'text/html',
    'content-length': '179',
    connection: 'close',
    'set-cookie': [
      '__cfduid=[redacted]; expires=Mon, 18-Jan-21 12:43:08 GMT; path=/; domain=.mmoui.com; HttpOnly; SameSite=Lax; Secure'
    ],
    'cache-control': 'no-store, no-cache',
    'cf-cache-status': 'DYNAMIC',
    'cf-request-id': '[redacted]',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report?s=[redacted]"}],"group":"cf-nel","max_age":604800}',
    nel: '{"report_to":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'cf-ray': '[redacted]'
  },
  body: '<html>\r\n' +
    '<head><title>520 Origin Error</title></head>\r\n' +
    '<body bgcolor="white">\r\n' +
    '<center><h1>520 Origin Error</h1></center>\r\n' +
    '<hr><center>cloudflare-nginx</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n'
}
```

Thank you

**Comment by antiwinter** [comment]
Thank you for the feedback. This issue is fixed and released in 1.3.13
